steps:
  # Build and image using existing Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/language-tool:4.8'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/language-tool:4.8'
      - '.'
  # Push an image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [ 'push', 'gcr.io/$PROJECT_ID/language-tool:4.8']
  # Deploy an image from Container Registry to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
    - 'run'
    - 'deploy'
    - 'docker-languagetool'
    - '--image'
    - 'gcr.io/$PROJECT_ID/language-tool:4.8'
    - '--region'
    - 'europe-west4'
    - '--port'
    - '8010'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
