steps:
  # Build image using existing Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/language-tool:latest'
      - '.'
images: ['gcr.io/$PROJECT_ID/language-tool:latest']